-- V1__init.sql
-- Phase 4.6: initial schema for kotlin-todo on PostgreSQL 17.
-- Mirrors docs/db-schema.md and the JPA entities under
-- backend/src/main/kotlin/com/example/kotlin_todo/domain/entity/.

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE categories (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    owner_id BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT categories_owner_name_unique UNIQUE (owner_id, name)
);

CREATE TABLE todos (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    due_date    DATE,
    priority    VARCHAR(20)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    category_id BIGINT       REFERENCES categories(id) ON DELETE SET NULL,
    owner_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_todos_owner_id     ON todos (owner_id);
CREATE INDEX idx_todos_owner_status ON todos (owner_id, status);
CREATE INDEX idx_todos_due_date     ON todos (due_date);